### ISSUE TITLE
How to use Options

### ISSUE THREAD

**Issue by Wuemeli** [TFAGaming/DiscordJS-Commands-Handler#1]
This is my Options:         options:  [options
        .setName("user")
        .setDescription("Select the user")
        .setRequired(true)
    ],
        options: [options 
        .setName("reason")
        .setDescription("Select the reason")
        .setRequired(false)

    ],

And i want to get the Value that the User has entered
How could i do this? And is the Option formatting Right?

**Comment by Wuemeli** [comment]
{
                name: 'user',
                description: 'The user to ban',
                type: 6,
                required: true,
              },
              {
                name: 'reason',
                description: 'The reason for banning the user',
                type: 3,
                required: false,
              },
        ],

So i thought this would be right? But how can i get the Value?

**Comment by TFAGaming** [comment]
From the [discord.js docs](https://discord.js.org/#/docs/discord.js/main/class/CommandInteractionOptionResolver), you can use the method `getUser()` to get the user value. Example:
```ts
// First method
const user = interaction.options?.getUser('user'); // 'user' because the option name is 'user'.
// Second method
const user = client.users.cache.get(interaction.options?.get('user')?.value); // 'user' because the option name is 'user'.
```

**Comment by Wuemeli** [comment]
Thanks
